### ISSUE TITLE
Error installing (dangling bash else statement)

### ISSUE THREAD

**Issue by mattharrison** [rapidsai/rapidsai-csp-utils#1]
When trying to following the install directions I get:

    rapidsai-csp-utils/colab/rapids-colab.sh: line 70: syntax error near unexpected token `else'

See:

https://github.com/rapidsai/rapidsai-csp-utils/blob/52e9c9df69e81ef8ff83f3029872176ef3f9847e/colab/rapids-colab.sh#L70

**Comment by chaitanya2692** [comment]
I managed to solve the issue by deleting lines 70 and 71 in rapids-colab.sh. The installation should be successful then. After installing, then you have to set the path for NVVM. Copy and paste the below lines to notebook cell.

`import os  
os.environ['NUMBAPRO_NVVM']='/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so'  
os.environ['NUMBAPRO_LIBDEVICE']='/usr/local/cuda-10.0/nvvm/libdevice'`

**Comment by chaitanya2692** [comment]
I managed to solve the issue by deleting lines 70 and 71 in rapids-colab.sh. The installation should be successful then. After installing, then you have to set the path for NVVM. Copy and paste the below lines to notebook cell.

`import os    
os.environ['NUMBAPRO_NVVM']='/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so' 
   
os.environ['NUMBAPRO_LIBDEVICE']='/usr/local/cuda-10.0/nvvm/libdevice'`

**Comment by gig67** [comment]
To be of practical help: 
I run the following code in a cell first
import os
import sys
import shutil

## Try to remove tree; if failed show an error using try...except on screen
try:
    shutil.rmtree('rapidsai-csp-utils')
except OSError as e:
    print ("Error: %s - %s." % (e.filename, e.strerror))

!git clone https://github.com/rapidsai/rapidsai-csp-utils.git
import sys, os
os.listdir()
fileToChange='./rapidsai-csp-utils/colab/rapids-colab.sh'
file1 = open(fileToChange, 'r') 
Lines = file1.readlines()
file1.close() 
Lines = Lines[:69]+Lines[71:] # delete offending lines

file1 = open(fileToChange, 'w') 
file1.writelines(Lines) 
file1.close() 

then in the following cell I run what is suggested on rapidsai model notebook, except the !Git clone instruction: 

!bash rapidsai-csp-utils/colab/rapids-colab.sh
import sys, os
dist_package_index = sys.path.index('/usr/local/lib/python3.6/dist-packages')
sys.path = sys.path[:dist_package_index] + ['/usr/local/lib/python3.6/site-packages'] + sys.path[dist_package_index:]
sys.path
exec(open('rapidsai-csp-utils/colab/update_modules.py').read(), globals())

I tried chaitanya2692 suggestion but colab says that environemntal variables starting with NUMBAPRO are deprecated and ignored. It works fine even without those.

**Comment by taureandyernv** [comment]
fixed in #2 Thanks!  I was trying to fix a UI issue, and I ended up introducing 1 else too many :-P

**Comment by taureandyernv** [comment]
@mattharrison , There is a new issue with 0.13 only, and that may be because of a nightlies issue.  I'll keep tracking it. 
 Thanks for posting, i wouldn't have seen it until i ran a full test again.

**Comment by prabindh** [comment]
The latest script does not work for me, I tried 0.13, as well as 0.11. 

Log for this colab session (with GPU runtime) is at,
https://colab.research.google.com/gist/prabindh/59c7126195cce4cffef96e4d63ea4d15/untitled5.ipynb

What could be the issue ?
