### ISSUE TITLE
Jupyter Notebook install

### ISSUE THREAD

**Issue by sublimotion** [rapidsai/rapidsai-csp-utils#21]
Would it be possible to use this script to run on a jupyter notebook instance as well?

In my case I am running a jupyter notebook on SageMaker.

**Comment by taureandyernv** [comment]
Hey @sublimotion !  If you prefer sagemaker, we have a sagemaker install process that works well: https://medium.com/rapids-ai/running-rapids-experiments-at-scale-using-amazon-sagemaker-d516420f165b.  [We also have a slack channel that you can join to discuss further](https://join.slack.com/t/rapids-goai/shared_invite/enQtMjE0Njg5NDQ1MDQxLTJiN2FkNTFkYmQ2YjY1OGI4NTc5Y2NlODQ3ZDdiODEwYmRiNTFhMzNlNTU5ZWJhZjA3NTg4NDZkMThkNTkxMGQ).

**Comment by taureandyernv** [comment]
Hpe the info helped.  I'm closing as no further response from OP :)
