### ISSUE TITLE
Google Colab demo notebook not working

### ISSUE THREAD

**Issue by jrdi** [rapidsai/rapidsai-csp-utils#36]
I've been trying to install rapids stable on a Google Colab notebook and didn't work. After trying many things, I've found the example notebook on your website (https://colab.research.google.com/drive/1rY7Ln6rEE1pOlfSHCYOVaqt8OvDO35J0#forceEdit=true&offline=true&sandboxMode=true) but it doesn't work also.

After executing the installation script successfully `import cudf` is raising the following error:

```bash
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-a95ca25217db> in <module>()
----> 1 import cudf
      2 import io, requests
      3 
      4 # download CSV file from GitHub
      5 url="https://github.com/plotly/datasets/raw/master/tips.csv"

5 frames
/usr/local/lib/python3.6/site-packages/llvmlite/binding/ffi.py in <module>()
    151         break
    152 else:
--> 153     raise OSError("Could not load shared object file: {}".format(_lib_name))
    154 
    155 

OSError: Could not load shared object file: libllvmlite.so
```

Any ideas or possible workarounds? I tried with `stable` and `nightly` but I'm getting the same error with both.

**Comment by LoFe** [comment]
Hi, 
There is a workaround:
Run this in a cell: 
`!find / -name libllvmlite.so* `
it will give you something like this: 
```
/usr/local/lib/python3.6/dist-packages/llvmlite/binding/libllvmlite.so
/usr/local/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so
/usr/local/lib/python2.7/dist-packages/llvmlite/binding/libllvmlite.so
/usr/local/pkgs/llvmlite-0.33.0-py36hfa65bc7_1/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so
/usr/local/pkgs/llvmlite-0.32.1-py36hfa65bc7_0/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so
/content/libllvmlite.so
```

Then cp the corresponding one to the current dir you are in (I did the following):
`!cp /usr/local/lib/python3.6/dist-packages/llvmlite/binding/libllvmlite.so . `

It also required a full restart on the notebook, but now it is working least for me.

**Comment by sshillo** [comment]
@jrdi I'm seeing this as well. @LoFe that solved the llvmlite issue but now i'm seeing
```
AttributeError: module 'numba' has no attribute 'core'
```
Have you seen this?

**Comment by maculjak** [comment]
@sshillo I had this issue as well.

**Comment by LoFe** [comment]
@jrdi @sshillo @maculjak
Oh yes, sorry i forgot it, I got this as well. :D I found (https://github.com/numba/numba/issues/6246) that this problem was solved in a newer version of numba, so we had to update it:
So hit the code below after you dud the cp command:
`!conda install -y -c conda-forge numba==0.49.1`

pls note that I'm not an expert in this and just want to find a quick solution (it may be dirty)

**Comment by maculjak** [comment]
@LoFe This solution indeed seems dirty, but it works. Thanks :)

**Comment by jaywu109** [comment]
@LoFe The solution also works for me. Many thanks!

**Comment by msserpa** [comment]
Thanks, @LoFe . It works for me too.

**Comment by hbouy** [comment]
Had the same issues and the solution works for me too
It should be integrated in the rapidsai-csp-utils/colab/rapids-colab.sh file!

**Comment by hbouy** [comment]
Encounter the same problem. Copying `libllvmlite.so` solve the first issue and to took me 1 step further.
I noticed in the log that `numba-0.50.1` had been installed, so I did not install `0.49.1` as suggested by @LoFe .
But trying to `import cudf` broke with the following error message:
`ImportError: Numba requires at least version 9.0.0 of LLVM. 
Installed llvmlite is built against version 8.0.0. 
Please update llvmlite.`

`llvmlite==0.33.0` was installed. So I installed llvm 9.0.0:
`!conda install -y -c conda-forge llvm=9.0.0`

But trying to `import cudf` then gave me the same error as @sshillo:
`AttributeError: module 'numba' has no attribute 'core'`
eventhough numba is 0.50.1 

am stuck...

**Comment by stonebig** [comment]
as a remark, I had the same error by installing numba , and trying to use it inside the same already running notebook. restarting the kernel (and reloading numba) solved the issue

**Comment by xia0nan** [comment]
It works for me following suggestions above:

1.  To solve error: 

> OSError: Could not load shared object file: libllvmlite.so

Use code as suggested by @LoFe 
`!find / -name libllvmlite.so*`
and cp one of the output to current dir:
`!cp /usr/local/lib/python3.6/dist-packages/llvmlite/binding/libllvmlite.so .`

and restart runtime.

2. To solve error:

> ImportError: Numba requires at least version 9.0.0 of LLVM. Installed llvmlite is built against version 8.0.0. Please update llvmlite.

Use code as suggested by @hbouy 
`!conda install -y -c conda-forge llvm=9.0.0`

and restart runtime.

3. Rerun the cell without running the bash script:
```# Install RAPIDS
# !git clone https://github.com/rapidsai/rapidsai-csp-utils.git
# !bash rapidsai-csp-utils/colab/rapids-colab.sh stable

import sys, os

dist_package_index = sys.path.index('/usr/local/lib/python3.6/dist-packages')
sys.path = sys.path[:dist_package_index] + ['/usr/local/lib/python3.6/site-packages'] + sys.path[dist_package_index:]
sys.path
exec(open('rapidsai-csp-utils/colab/update_modules.py').read(), globals())
```

Then we can have the output like below:
![Screenshot 2020-12-30 at 4 03 55 PM](https://user-images.githubusercontent.com/2216266/103338311-efa5f200-4ab8-11eb-91c9-fa75de9dbedd.png)

I did not encounter the error `AttributeError: module 'numba' has no attribute 'core'` since during install the `llvm=9.0.0`, it downgrade the numba package:
```
The following packages will be DOWNGRADED:

  libllvm9                                 9.0.1-hf817b99_2 --> 9.0.0-hc9558a2_3
  llvmlite                            0.33.0-py36hfa65bc7_1 --> 0.33.0-py36hfa65bc7_0
  numba                               0.50.1-py36h0573a6f_1 --> 0.50.1-py36h0573a6f_0
```

**Comment by taureandyernv** [comment]
Hey @xia0nan @stonebig @jrdi @sshillo @maculjak @LoFe 

I wanted to thank you for your exploration of this issue.  I've pushed a commit that fixes this issue.   

It is unfortunate that we are not able to keep Google as up to date as other solutions, such as https://app.blazingsql.com.  This is beyond our control.  We do suggest that you use those solutions for trying out RAPIDS as it runs the most current stable and nightly versions.

I do want to share with the community a method of testing and updating the colab script that is much easier than some of the methods I saw discussed above.  If you are interested in that, please let me know and i'll share a link with you all and/or add it into the README

I will close the issue, as it is solved, but will keep monitoring the issue for your replies.

**Comment by hbouy** [comment]
Hi!

I am indeed interested, please send me the link

Thank you

Herve

**Comment by taureandyernv** [comment]
https://colab.research.google.com/drive/11qtx9BcKdklezvuMEcAHmOUAc5Z40dyq?usp=sharing

Made just for you (and everyone else).  Enjoy!

**Comment by LoFe** [comment]
> Hey @xia0nan @stonebig @jrdi @sshillo @maculjak @LoFe @@jrdi @sshillo @hbouy
> 
> I wanted to thank you for your exploration of this issue. I've pushed a commit that fixes this issue.
> 
> It is unfortunate that we are not able to keep Google as up to date as other solutions, such as https://app.blazingsql.com. This is beyond our control. We do suggest that you use those solutions for trying out RAPIDS as it runs the most current stable and nightly versions.
> 
> I do want to share with the community a method of testing and updating the colab script that is much easier than some of the methods I saw discussed above. If you are interested in that, please let me know and i'll share a link with you all and/or add it into the README
> 
> I will close the issue, as it is solved, but will keep monitoring the issue for your replies.

I'm definitely interested in your solution/script! Thanks
