### ISSUE TITLE
Error Installing RAPIDS on Google Colab

### ISSUE THREAD

**Issue by dam2217** [rapidsai/rapidsai-csp-utils#38]
I keep getting this error when I try running the rapids-colab.ipynb. I'm quite new to using Google Colab so I'm not sure if it is something I am doing wrong on my end. 
![image](https://user-images.githubusercontent.com/52660064/108987970-d0c47600-768b-11eb-87e5-9b55af855e43.png)
![image](https://user-images.githubusercontent.com/52660064/108987064-c2c22580-768a-11eb-80fc-79a3b50e598f.png)

**Comment by Nerkan78** [comment]
I changed python3.6 to python3.7 folder and this cell worked correct. You can see in `sys.path` variable  that there is python3.7 now. However, next `import cudf` failed with `ModuleNotFindError`. As far as I understand it is connected with different versions.

**Comment by taureandyernv** [comment]
Thanks @Nerkan78 , I solved the issue with PR #40  with help from @jrdi in #39
