### ISSUE TITLE
Miniconda Latest has been upgraded to python 3.8

### ISSUE THREAD

**Issue by mberlinger3** [rapidsai/rapidsai-csp-utils#41]
Results in a long downgrade process

```
The following packages will be DOWNGRADED:

  python                                   3.8.5-h7579374_1 --> 3.7.10-hdb3f193_0
```

EDIT: the latest python 3.7 release is: Miniconda3-py37_4.9.2-Linux-x86_64.sh

**Comment by mberlinger3** [comment]
heres a patch for those who want to revert in colab

```python
#Fix Miniconda
miniconda_latest ='Miniconda3-latest-Linux-x86_64.sh'
miniconda_py37='Miniconda3-py37_4.9.2-Linux-x86_64.sh'

with open('rapidsai-csp-utils/colab/rapids-colab.sh', 'r') as file:
    install_script = file.readlines()

install_script = [line.replace(miniconda_latest,miniconda_py37) for line in install_script]

with open('rapidsai-csp-utils/colab/rapids-colab.sh', 'w') as file:
    file.writelines(install_script)
```

**Comment by taureandyernv** [comment]
Hey @mberlinger3  thanks for the tip!

I tested your method by editing the actual code.  I got 941 seconds (15 minutes). What speedup were you experiencing?  

Either way, I'm going to add it to `main`, i was just curious on what you saw in case I should have had different expectations.

**Comment by taureandyernv** [comment]
Solved with https://github.com/rapidsai/rapidsai-csp-utils/pull/46.  Closing.  Thanks again @mberlinger3 !
