### ISSUE TITLE
[FEA] add option to bypass prompt

### ISSUE THREAD

**Issue by pboudier** [rapidsai/rapidsai-csp-utils#8]
when using the script rapidsai-csp-utils/colab/rapids-colab.sh to enable rapids in a colab environment, there are two prompts:
- one for the version number
- one to verify the script is up to date

after one goes through the trouble of using that script, one always answers the same to those prompts, and it is cumbersome when restarting notebook, especially given that the entire process takes a while.

it would be nice to have a CLI to bypass those options, for instance to specify the version of rapids, and to bypass the check.

another useful commandline would be to specify a subset of the libraries that is intended to be used. For instance, I have used RAPIDS to have quick evaluation using TSNE, and would like to just install cuml on that instance.

**Comment by taureandyernv** [comment]
Hey @pboudier!  Thanks for the sugguestions

We are going to remove some of the verbiage and prompts for 0.13 release, as it was there as a PSA to help people through the massive changes with how to setup up Colab between v0.11 and now.  I can look at updating the script with CLI options.  

We do recommend that Colab be used for showing off RAPIDS to those without GPU or short term Linux access and that we suggest frequent users looking for performance provision a GPU through more persistent avenues.

However, while we keep the install script up to date we cannot verify that everything in your install cell is up to date.  We don't currently work *with* Colab, we work *around* Colab.  If you miss a step in that cell, the updates when installing RAPIDS that the script makes may not take in Colab.  Very much outside of our control.

**Comment by taureandyernv** [comment]
closed with #9 and #10.  will update install scripts on colab
